FROM ruby:2.6

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        nodejs \
    && gem install bundler \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
